apiVersion: apps/v1
kind: Deployment
metadata:
  name: downward-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: downward
  template:
    metadata:
      labels:
        app: downward
    spec:
      containers:
        - name: env-container
          image: bash:latest
          command: ["/bin/sh", "-c", "env"]
          resources:
            requests:
              memory: "32Mi"
              cpu: "125m"
            limits:
              memory: "64Mi"
              cpu: "250m"
#          通过执行命令进行判断
#          livenessProbe:
#            exec:
#              command:
#                - cat
#                - /tmp/health
#          通过能否建立TCP连接
#          livenessProbe:
#            tcpSocket:
#              port: 80
#          通过APP自身的Health point
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 80
#              initialDelaySeconds: 30
#              timeoutSeconds: 1
#          startupProbe:
#            httpGet:
#              path: /healthz
#              port: 80
#            failureThreshold: 30
#            periodSeconds: 10
#          Springboot 2.3.0 now support liveness and readiness health point
#          readinessProbe:
#            exec:
#              command:
#                - cat
#                - /tmp/healthy
#            initialDelaySeconds: 5
#            periodSeconds: 5
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: env-container
                  resource: requests.cpu
            - name: MEM_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: env-container
                  resource: limits.memory
