apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      volumes:
        - name: datavol
          emptyDir: {}
        - name: service-config
          configMap:
            name: hello-config
            # 若没有以下的部分则会对每个key都生成一个文件
            items:
              - key: application.yml
                path: application.yml
      containers:
        - name: hello-service
          image: loadtest_hello:latest
# Load all env vars
#          envFrom:
#             - configMapRef:
#                 name: hello-config
# Load each env var
#          env:
#            - name: AUTHORNAME
#              valueFrom:
#                configMapKeyRef:
#                  name: hello-config
#                  key: yutian
#            - name: CONTENT
#              valueFrom:
#                configMapKeyRef:
#                  name: hello-config
#                  key: hello
          volumeMounts:
            - mountPath: /hello-data
              name: datavol
            - name: service-config
              mountPath: /configs
          ports:
            - containerPort: 8082
          imagePullPolicy: Never
          resources:
            limits:
              cpu: 500m
            requests: ## Mandatory for horizontal pod autoscaler
              cpu: 200m